### PR TITLE
Add MIT license

### LINKED ISSUE #60: Repository does not officially contain a license
Currently, the repository does not have an explicit license in `LICENSE.md/txt` or mention one in `README.md`. In `package.json`, it is listed that we are under `MIT`, but due to the low visibility of this, it does not explicitly say. Not having an explicit license could possibly lead to issues down the line.

Before the release of 1.0.0, we should make this change.

### PR DESCRIPTION
**Pull request by TheIceCreamBear**
All team members must approve this PR and add a comment to acknowledge the new license and consent to their code being licensed under the MIT license.

The following example comment is valid. Anything similar that shows explicit permission for the license is acceptable.
> I agree that all my contributions to this project can be licensed under MIT License.

(Fixes #60)

## Team members who need to consent:
- [x] @cwsCarlson 
- [x] @Iantho1999 
- [x] @RyanG10 
- [x] @Effectualness 
- [x] @TheIceCreamBear 

## Personal note of consent
And for completeness, I personally consent that all of my contributions to this project and repositor can be licensed under the MIT license.

### CODE REVIEW

**Comment by cwsCarlson** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by Effectualness** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Review by Effectualness — APPROVED** [review]

**Review by Iantho1999 — APPROVED** [review]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by RyanG10** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Review by RyanG10 — APPROVED** [review]

**Review by cwsCarlson — APPROVED** [review]

**Pull request merged**
